# Generated by Django 6.0.1 on 2026-01-23 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_profile_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="template_file",
            field=models.FileField(blank=True, null=True, upload_to="project_templates/"),
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_id", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")], default="DRAFT", max_length=20)),
                ("answer_data", models.JSONField(blank=True, default=dict)),
                ("remark_data", models.JSONField(blank=True, default=dict)),
                ("image_data", models.JSONField(blank=True, default=dict)),
                ("template_copy", models.FileField(blank=True, null=True, upload_to="checklists/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklists", to="core.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
