# Generated by Django 6.0.1 on 2026-01-24 00:00

from django.db import migrations, models


def migrate_completed_to_final(apps, schema_editor):
    Checklist = apps.get_model("core", "Checklist")
    Checklist.objects.filter(status="COMPLETED").update(status="FINAL")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_template_checklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="status",
            field=models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("REVIEW", "Review"), ("FINAL", "Final")], default="DRAFT", max_length=20),
        ),
        migrations.AddField(
            model_name="checklist",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(migrate_completed_to_final, migrations.RunPython.noop),
    ]
