# Generated by Django 6.0.1 on 2026-01-24 00:00

from django.db import migrations, models
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_checklist_status_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="template_file",
            field=models.FileField(blank=True, null=True, upload_to=core.models.project_template_upload_path),
        ),
    ]
