# Generated by Django 6.0.1 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_template_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
