# Generated by Django 6.0.1 on 2026-01-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_template_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Leader'), ('ENGINEER', 'Engineer')], max_length=20),
        ),
    ]
