# Generated by Django 6.0.1 on 2026-01-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_role'),
        ('core', '0006_profile_lockout'),
    ]

    operations = [
    ]
