# Generated by Django 6.0.1 on 2026-01-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='checklist',
            field=models.OneToOneField(blank=True, help_text='Auto-created checklist for this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignment', to='core.checklist'),
        ),
    ]
