# Generated by Django 6.0.1 on 2026-01-25 00:09

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workassignment_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('row_number', models.IntegerField()),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.checklist')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('checklist', 'section_name', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.checklist_image_upload_path)),
                ('column_position', models.CharField(default='F', max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.checklist')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.checklistsection')),
            ],
            options={
                'ordering': ['column_position', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('position_index', models.IntegerField(default=0)),
                ('voltage', models.CharField(blank=True, max_length=100)),
                ('current_r', models.CharField(blank=True, max_length=100)),
                ('current_y', models.CharField(blank=True, max_length=100)),
                ('current_b', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_data', to='core.checklist')),
            ],
            options={
                'ordering': ['position_index'],
            },
        ),
        migrations.CreateModel(
            name='TowerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_type', models.CharField(choices=[('STC', 'STC'), ('OTHER', 'Other Operator')], max_length=10)),
                ('equipment_type', models.CharField(choices=[('ANTENNA', 'Antenna Model'), ('RADIO', 'Radio Model'), ('FPFH', 'FPFH'), ('MICROWAVE', 'Microwave Model')], max_length=20)),
                ('row_number', models.IntegerField()),
                ('position_index', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('azimuth', models.CharField(blank=True, max_length=100)),
                ('empty_port', models.CharField(blank=True, max_length=100)),
                ('sector_or_leg', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_equipment', to='core.checklist')),
            ],
            options={
                'ordering': ['operator_type', 'equipment_type', 'position_index'],
            },
        ),
        migrations.CreateModel(
            name='DCPowerSystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('field_label', models.CharField(max_length=200)),
                ('field_value', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_power_data', to='core.checklist')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('checklist', 'row_number')},
            },
        ),
    ]
