# Generated by Django 6.0.1 on 2026-02-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_checklistsection_checklistimage_electricaldata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='site_id',
            field=models.CharField(help_text='Site identification number (unique)', max_length=120, unique=True),
        ),
    ]
